import edu.rit.ds.RemoteEvent;

/**
 * @author Ganesh Chandrasekaran
 * @version 04-20-2013
 */

/**
 * Class TrackPackage encapsulates a remote event generated by a GPSOffice in
 * the GPSOffice system. The TrackPackage events are used to report status of
 * the packages to the Customer and Headquarters programs
 */
public class TrackPackage extends RemoteEvent {
	public final long packageID;
	public final String message;
	public final int status;

	/**
	 * Create a new TrackPackage event.
	 * 
	 * @param notification
	 *            String
	 * @param packetNumber
	 *            long
	 * @param s
	 *            int
	 */
	public TrackPackage(String notification, long packetNumber, int s) {
		this.packageID = packetNumber;
		this.message = notification;
		this.status = s;
	}
}